-- Seed data generated from the current 13-group timetable. Run AFTER schema.sql.
-- Safe to re-run: it clears and re-inserts both tables (any live admin edits made
-- through the admin page since the last time you ran this WILL be overwritten).
delete from public.lectures;
delete from public.courses;

insert into public.courses (code, title_en, title_ar) values
  ('CAI115', 'CAI115 – Introduction to Computer Science', 'CAI115 – مقدمة في علوم الحاسب'),
  ('BSC111', 'BSC111 – Physics', 'BSC111 – فيزياء'),
  ('BSC112', 'BSC112 – Calculus I', 'BSC112 – تفاضل وتكامل (1)'),
  ('BSC114', 'BSC114 – Discrete Mathematics', 'BSC114 – رياضيات متقطعة'),
  ('UNI101', 'UNI101 – Professional Ethics and Legal Aspects', 'UNI101 – أخلاقيات المهنة والجوانب القانونية'),
  ('UNI109', 'UNI109 – Critical Thinking and Problem-Solving', 'UNI109 – التفكير الناقد وحل المشكلات'),
  ('MATH0', 'Math 0 – Mathematics 0', 'Math 0 – رياضيات صفر'),
  ('COMM', 'Community Activities', 'الأنشطة الطلابية');

insert into public.lectures (group_key, day, period, code, type, room, staff, staff_ar, alt) values
  ('GA8', 'sun', 1, 'CAI115', 'Lecture', 'C333', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA8', 'sun', 2, 'BSC111', 'Lecture', 'C333', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GA8', 'sun', 3, 'UNI109', 'Laboratory', 'P.L.C228', 'L.A. Ganna', 'م.م جنا', null),
  ('GA8', 'mon', 1, 'BSC114', 'Lecture', 'C201', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GA8', 'mon', 2, 'BSC112', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GA8', 'mon', 3, 'UNI101', 'Lecture', 'C201', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GA8', 'mon', 4, 'UNI109', 'Lecture', 'C201', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GA8', 'tue', 1, 'CAI115', 'Laboratory', 'P.L.C334', '', 'م.م إنجي، م.م خالد', null),
  ('GA8', 'tue', 2, 'BSC111', 'Laboratory', 'Phys. Lab', '', 'م.م مؤمن، م.م جانا', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','','staff_ar','م.م مؤمن، م.م جانا')),
  ('GA8', 'tue', 3, 'COMM', 'Community Activity', 'C333', '', '', null),
  ('GA8', 'wed', 3, 'MATH0', 'Section', 'C224', 'T.A. A. Othman', 'م.م أ.عثمان', null),
  ('GA8', 'thu', 1, 'BSC112', 'Exercise', 'C223', 'L.A. Asmaa, T.A. Albaraa', 'م.م أسماء، م.م البراء', null),
  ('GA8', 'thu', 2, 'BSC114', 'Exercise', 'C430', 'T.A. Yousef, T.A. M. Esmaeel', 'م.م يوسف، م.م إسماعيل', null),
  ('GA8', 'thu', 3, 'MATH0', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa, Dr. Marwa', 'أ.د رامي، د.نجلاء، د.مروة', null),
  ('GA6', 'sun', 1, 'CAI115', 'Lecture', 'C333', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA6', 'sun', 2, 'BSC111', 'Lecture', 'C333', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GA6', 'sun', 4, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GA6', 'mon', 1, 'BSC114', 'Lecture', 'C201', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GA6', 'mon', 2, 'BSC112', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GA6', 'mon', 3, 'UNI101', 'Lecture', 'C201', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GA6', 'mon', 4, 'UNI109', 'Lecture', 'C201', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GA6', 'tue', 1, 'BSC111', 'Laboratory', 'Phys. Lab', '', 'م.م مؤمن، م.م جانا', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','','staff_ar','م.م مؤمن، م.م جانا')),
  ('GA6', 'tue', 2, 'CAI115', 'Laboratory', 'P.L.C334', 'L.A. Engy, T.A. M.Khaled', 'م.م إنجي، م.م خالد', null),
  ('GA6', 'tue', 3, 'COMM', 'Community Activity', 'C333', '', '', null),
  ('GA6', 'tue', 4, 'MATH0', 'Section', 'C224', 'T.A. A. Othman', 'م.م أ.عثمان', null),
  ('GA6', 'thu', 1, 'BSC114', 'Exercise', 'C430', 'T.A. Yousef, T.A. M. Esmaeel', 'م.م يوسف، م.م إسماعيل', null),
  ('GA6', 'thu', 2, 'UNI109', 'Laboratory', 'P.L.C334', 'L.A. Shahd', 'م.م شهد', null),
  ('GA6', 'thu', 3, 'MATH0', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa, Dr. Marwa', 'أ.د رامي، د.نجلاء، د.مروة', null),
  ('GC1', 'sun', 1, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GC1', 'sun', 2, 'BSC112', 'Exercise', 'C223', 'L.A. Asmaa, T.A. Albaraa', 'م.م أسماء، م.م البراء', null),
  ('GC1', 'sun', 3, 'UNI101', 'Lecture', 'C135', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GC1', 'sun', 4, 'UNI109', 'Lecture', 'C135', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GC1', 'mon', 1, 'BSC111', 'Exercise', 'C432', 'L.A. Toqa, T.A. Habeba', 'م.م توقى، م.م حبيبة', jsonb_build_object('type','Exercise','room','C432','staff','L.A. Toqa, T.A. Habeba','staff_ar','م.م توقى، م.م حبيبة')),
  ('GC1', 'mon', 2, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GC1', 'mon', 4, 'BSC114', 'Exercise', 'C331', 'L.A. Amira, T.A. May', 'م.م أميرة، م.م مي', null),
  ('GC1', 'tue', 1, 'UNI109', 'Laboratory', 'P.L.C435', 'L.A. Mariam', 'م.م مريم', null),
  ('GC1', 'tue', 3, 'COMM', 'Community Activity', 'C141', '', '', null),
  ('GC1', 'wed', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GC1', 'wed', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GC1', 'thu', 1, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GC2', 'sun', 1, 'CAI115', 'Laboratory', 'P.L.C334', 'L.A. Amir, T.A. Nada', 'م.م أمير، م.م ندى', null),
  ('GC2', 'sun', 2, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GC2', 'sun', 3, 'UNI101', 'Lecture', 'C135', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GC2', 'sun', 4, 'UNI109', 'Lecture', 'C135', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GC2', 'mon', 1, 'BSC111', 'Laboratory', 'Phys. Lab', 'L.A. Danial, T.A. Shaimaa', 'م.م دانيال، م.م شيماء', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','L.A. Danial, T.A. Shaimaa','staff_ar','م.م دانيال، م.م شيماء')),
  ('GC2', 'mon', 2, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GC2', 'mon', 4, 'BSC114', 'Exercise', 'C222', 'L.A. Dina, T.A. Ziad', 'م.م دينا، م.م زياد', null),
  ('GC2', 'tue', 2, 'UNI109', 'Laboratory', 'P.L.C435', 'L.A. Alieldeen', 'م.م علي الدين', null),
  ('GC2', 'tue', 3, 'COMM', 'Community Activity', 'C141', '', '', null),
  ('GC2', 'wed', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GC2', 'wed', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GC2', 'thu', 1, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GD2', 'sun', 1, 'BSC114', 'Exercise', 'C430', 'T.A. Yousef, T.A. M. Esmaeel', 'م.م يوسف، م.م إسماعيل', null),
  ('GD2', 'sun', 3, 'UNI109', 'Lecture', 'C209', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GD2', 'sun', 4, 'UNI101', 'Lecture', 'C209', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GD2', 'mon', 1, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GD2', 'mon', 2, 'BSC112', 'Exercise', 'C223', 'L.A. Asmaa, T.A. Albaraa', 'م.م أسماء، م.م البراء', null),
  ('GD2', 'mon', 3, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GD2', 'mon', 4, 'BSC111', 'Laboratory', 'Phys. Lab', 'L.A. Danial, T.A. Shaimaa', 'م.م دانيال، م.م شيماء', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','L.A. Danial, T.A. Shaimaa','staff_ar','م.م دانيال، م.م شيماء')),
  ('GD2', 'tue', 2, 'UNI109', 'Laboratory', 'P.L.C220', 'L.A. Shahd', 'م.م شهد', null),
  ('GD2', 'tue', 3, 'COMM', 'Community Activity', 'C101', '', '', null),
  ('GD2', 'wed', 3, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GD2', 'thu', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GD2', 'thu', 3, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA7', 'sun', 1, 'CAI115', 'Lecture', 'C333', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA7', 'sun', 2, 'BSC111', 'Lecture', 'C333', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GA7', 'sun', 3, 'UNI109', 'Laboratory', 'P.L.C334', 'L.A. Alieldeen', 'م.م علي الدين', null),
  ('GA7', 'sun', 4, 'BSC112', 'Exercise', 'C329', 'T.A. M. Ayman, T.A. M. Mostafa', 'م.م أيمن، م.م مصطفى', null),
  ('GA7', 'mon', 1, 'BSC114', 'Lecture', 'C201', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GA7', 'mon', 2, 'BSC112', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GA7', 'mon', 3, 'UNI101', 'Lecture', 'C201', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GA7', 'mon', 4, 'UNI109', 'Lecture', 'C201', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GA7', 'tue', 1, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr, T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GA7', 'tue', 2, 'BSC111', 'Exercise', 'C432', 'L.A. Toqa, T.A. Habeba', 'م.م توقى، م.م حبيبة', jsonb_build_object('type','Exercise','room','C432','staff','L.A. Toqa, T.A. Habeba','staff_ar','م.م توقى، م.م حبيبة')),
  ('GA7', 'tue', 3, 'COMM', 'Community Activity', 'C333', '', '', null),
  ('GA7', 'wed', 3, 'MATH0', 'Section', 'C224', 'T.A. A. Othman', 'م.م أ.عثمان', null),
  ('GA7', 'thu', 2, 'BSC114', 'Exercise', 'C222', 'L.A. Dina, T.A. Ziad', 'م.م دينا، م.م زياد', null),
  ('GA7', 'thu', 3, 'MATH0', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa, Dr. Marwa', 'أ.د رامي، د.نجلاء، د.مروة', null),
  ('GD3', 'sun', 1, 'UNI109', 'Laboratory', 'P.L.C220', 'L.A. Ganna', 'م.م جنا', null),
  ('GD3', 'sun', 2, 'BSC114', 'Exercise', 'C331', 'L.A. Amira, T.A. May', 'م.م أميرة، م.م مي', null),
  ('GD3', 'sun', 3, 'UNI109', 'Lecture', 'C209', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GD3', 'sun', 4, 'UNI101', 'Lecture', 'C209', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GD3', 'mon', 1, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GD3', 'mon', 2, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GD3', 'mon', 3, 'CAI115', 'Laboratory', 'P.L.C334', 'L.A. Amir, T.A. Nada', 'م.م أمير، م.م ندى', null),
  ('GD3', 'tue', 3, 'COMM', 'Community Activity', 'C101', 'Unassigned', 'غير محدد', null),
  ('GD3', 'wed', 1, 'BSC111', 'Exercise', 'C432', 'L.A. Toqa, T.A. Habeba', 'م.م توقى، م.م حبيبة', jsonb_build_object('type','Exercise','room','C432','staff','L.A. Toqa, T.A. Habeba','staff_ar','م.م توقى، م.م حبيبة')),
  ('GD3', 'wed', 3, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GD3', 'thu', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GD3', 'thu', 3, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GB4', 'sun', 1, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GB4', 'sun', 2, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GB4', 'mon', 1, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GB4', 'mon', 2, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr, T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GB4', 'mon', 3, 'UNI109', 'Lecture', 'C209', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GB4', 'mon', 4, 'UNI101', 'Lecture', 'C209', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GB4', 'tue', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GB4', 'tue', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GB4', 'tue', 3, 'COMM', 'Community Activity', 'C209', '', '', null),
  ('GB4', 'tue', 4, 'BSC111', 'Laboratory', 'Phys. Lab', 'L.A. Danial, T.A. Shaimaa', 'م.م دانيال، م.م شيماء', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','L.A. Danial, T.A. Shaimaa','staff_ar','م.م دانيال، م.م شيماء')),
  ('GB4', 'wed', 1, 'BSC114', 'Exercise', 'C331', 'L.A. Amira, T.A. May', 'م.م أميرة، م.م مي', null),
  ('GB4', 'wed', 3, 'UNI109', 'Laboratory', 'P.L.C220', 'L.A. Mariam', 'م.م مريم', null),
  ('GC4', 'sun', 1, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GC4', 'sun', 2, 'CAI115', 'Laboratory', 'P.L.C334', 'L.A. Amir, T.A. Nada', 'م.م أمير، م.م ندى', null),
  ('GC4', 'sun', 3, 'UNI101', 'Lecture', 'C135', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GC4', 'sun', 4, 'UNI109', 'Lecture', 'C135', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GC4', 'mon', 1, 'BSC114', 'Exercise', 'C430', 'T.A. Yousef, T.A. M. Esmaeel', 'م.م يوسف، م.م إسماعيل', null),
  ('GC4', 'mon', 2, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GC4', 'mon', 3, 'BSC111', 'Laboratory', 'Phys. Lab', 'L.A. Danial, T.A. Shaimaa', 'م.م دانيال، م.م شيماء', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','L.A. Danial, T.A. Shaimaa','staff_ar','م.م دانيال، م.م شيماء')),
  ('GC4', 'tue', 3, 'COMM', 'Community Activity', 'C141', '', '', null),
  ('GC4', 'wed', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GC4', 'wed', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GC4', 'thu', 1, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA1', 'sun', 1, 'CAI115', 'Lecture', 'C333', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GA1', 'sun', 2, 'BSC111', 'Lecture', 'C333', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GA1', 'sun', 3, 'BSC111', 'Exercise', 'C432', 'L.A. Toqa, T.A. Habeba', 'م.م توقى، م.م حبيبة', jsonb_build_object('type','Exercise','room','C432','staff','L.A. Toqa, T.A. Habeba','staff_ar','م.م توقى، م.م حبيبة')),
  ('GA1', 'sun', 4, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr, T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GA1', 'mon', 1, 'BSC114', 'Lecture', 'C201', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GA1', 'mon', 2, 'BSC112', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GA1', 'mon', 3, 'UNI101', 'Lecture', 'C201', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GA1', 'mon', 4, 'UNI109', 'Lecture', 'C201', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GA1', 'tue', 1, 'BSC112', 'Exercise', 'C225', 'L.A. Andro, T.A. Heba', 'م.م أندرو، م.م هبة', null),
  ('GA1', 'tue', 2, 'BSC114', 'Exercise', 'C331', 'L.A. Amira, T.A. May', 'م.م أميرة، م.م مي', null),
  ('GA1', 'tue', 3, 'COMM', 'Community Activity', 'C333', '', '', null),
  ('GA1', 'tue', 4, 'MATH0', 'Section', 'C330', 'T.A. Shahd Abdelsalam', 'م.م شهد عبدالسلام', null),
  ('GA1', 'thu', 1, 'UNI109', 'Laboratory', 'P.L.C220', 'L.A. Alieldeen', 'م.م علي الدين', null),
  ('GA1', 'thu', 3, 'MATH0', 'Lecture', 'C201', 'Prof. Ramy, Dr. Naglaa, Dr. Marwa', 'أ.د رامي، د.نجلاء، د.مروة', null),
  ('GB2', 'sun', 1, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GB2', 'sun', 2, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GB2', 'mon', 1, 'CAI115', 'Laboratory', 'P.L.C334', 'L.A. Amir, T.A Nada', 'م.م أمير، م.م ندى', null),
  ('GB2', 'mon', 2, 'BSC111', 'Laboratory', 'Phys. Lab', '', 'م.م مؤمن، م.م جانا', jsonb_build_object('type','Laboratory','room','Phys. Lab','staff','','staff_ar','م.م مؤمن، م.م جانا')),
  ('GB2', 'mon', 3, 'UNI109', 'Lecture', 'C209', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GB2', 'mon', 4, 'UNI101', 'Lecture', 'C209', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GB2', 'tue', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GB2', 'tue', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GB2', 'tue', 3, 'COMM', 'Community Activity', 'C209', '', '', null),
  ('GB2', 'tue', 4, 'BSC114', 'Exercise', 'C222', 'L.A. Dina, T.A. Ziad', 'م.م دينا، م.م زياد', null),
  ('GB2', 'wed', 1, 'BSC112', 'Exercise', 'C329', 'T.A. M. Ayman, T.A. M. Mostafa', 'م.م أيمن، م.م مصطفى', null),
  ('GB2', 'wed', 3, 'UNI109', 'Laboratory', 'P.L.C334', 'L.A. Ganna', 'م.م جنا', null),
  ('GC5', 'sun', 1, 'BSC112', 'Exercise', 'C329', 'T.A. M. Ayman, T.A. M. Mostafa', 'م.م أيمن، م.م مصطفى', null),
  ('GC5', 'sun', 2, 'UNI109', 'Laboratory', 'P.L.C220', 'L.A. Mariam', 'م.م مريم', null),
  ('GC5', 'sun', 3, 'UNI101', 'Lecture', 'C135', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GC5', 'sun', 4, 'UNI109', 'Lecture', 'C135', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GC5', 'mon', 1, 'CAI115', 'Laboratory', 'P.L.C220', 'L.A. Engy, T.A. M.Khaled', 'م.م إنجي، م.م خالد', null),
  ('GC5', 'mon', 2, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GC5', 'mon', 4, 'BSC114', 'Exercise', 'C430', 'T.A. Yousef, T.A. M. Esmaeel', 'م.م يوسف، م.م إسماعيل', null),
  ('GC5', 'tue', 3, 'COMM', 'Community Activity', 'C141', '', '', null),
  ('GC5', 'wed', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GC5', 'wed', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GC5', 'wed', 3, 'BSC111', 'Exercise', 'C432', '', 'م.م مؤمن، م.م جانا', jsonb_build_object('type','Exercise','room','C432','staff','','staff_ar','م.م مؤمن، م.م جانا')),
  ('GC5', 'thu', 1, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null),
  ('GC3', 'sun', 1, 'BSC112', 'Exercise', 'C223', 'L.A. Asmaa, T.A. Albaraa', 'م.م أسماء، م.م البراء', null),
  ('GC3', 'sun', 2, 'CAI115', 'Laboratory', 'P.L.C228', 'T.A. Amr T.A. Ayman', 'م.م عمرو، م.م أيمن', null),
  ('GC3', 'sun', 3, 'UNI101', 'Lecture', 'C135', 'Prof. Hany, Dr. Bahaa', 'أ.د هاني، د.بهاء', null),
  ('GC3', 'sun', 4, 'UNI109', 'Lecture', 'C135', 'Prof. Rania, Dr. Abdullah', 'أ.د رانيا، د.عبدالله', null),
  ('GC3', 'mon', 1, 'BSC114', 'Exercise', 'C222', 'L.A. Dina, T.A. Ziad', 'م.م دينا، م.م زياد', null),
  ('GC3', 'mon', 2, 'BSC111', 'Lecture', 'C209', 'Prof. Hany, Dr. Kareem, Dr. Ahmed Fawzy', 'أ.د هاني، د.كريم، د.أحمد فوزي', null),
  ('GC3', 'mon', 3, 'BSC111', 'Exercise', 'C432', 'L.A. Toqa, T.A. Habeba', 'م.م توقى، م.م حبيبة', jsonb_build_object('type','Exercise','room','C432','staff','L.A. Toqa, T.A. Habeba','staff_ar','م.م توقى، م.م حبيبة')),
  ('GC3', 'tue', 3, 'COMM', 'Community Activity', 'C141', '', '', null),
  ('GC3', 'tue', 4, 'UNI109', 'Laboratory', 'P.L.C435', 'L.A. Alieldeen', 'م.م علي الدين', null),
  ('GC3', 'wed', 1, 'BSC112', 'Lecture', 'C209', 'Prof. Ramy, Dr. Naglaa', 'أ.د رامي، د.نجلاء', null),
  ('GC3', 'wed', 2, 'BSC114', 'Lecture', 'C209', 'Prof. Ramy, Dr. Marwa, Dr. Lamya', 'أ.د رامي، د.مروة، د.لمياء', null),
  ('GC3', 'thu', 1, 'CAI115', 'Lecture', 'C209', 'Prof. Rania, Dr. Yasser, Dr. Ghada', 'أ.د رانيا، د.ياسر، د.غادة', null);
